[package]
name = "ben"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
log = "0.4"
env_logger = { version = "0.11", features = ["color"] }
chrono = "0.4"
