version: 1

routes:
  - localhost:
    domain: localhost
    port: 8000
    protocol: http
    external_path: /api/identity/register
    internal_path: /api/identity/register
    methods:
      - POST
      - GET

  - google:
    domain: google.com
    port: 443
    protocol: https
    external_path: /identity/register/v2
    internal_path: /api/identity/register/v2
    methods:
      - POST
      - GET
